name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.18.0  
  image_picker: ^0.8.5+3  
  file_picker: ^5.2.4 
  flutter_slidable: ^0.6.0 
  reorderables: ^0.4.0
  supabase_flutter: ^2.0.0
  flutter_dotenv: ^5.1.0
  url_launcher: ^6.1.11
  mime: ^1.0.4
  path_provider: ^2.1.1
  universal_io: ^2.0.4
  uuid: ^4.1.0
  path: ^1.8.3  # For path manipulation
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
